### ISSUE TITLE
Produtos Configuráveis

### ISSUE THREAD

**Issue by claudiobiato** [brunoosilva/parcelamento-no-magento#1]
Olá Bruno, instalei mas infelizmente não funcionou para produtos configuráveis. A primeira opção do produto ele parcela normalmente, Como a segunda opção o valor é diferente ele não parcela, continua apresentando o primeiro valor. vc já se deparou com esse erro ?

**Comment by brunoosilva** [comment]
Opa, desculpa a demora de 2 anos, rs

Mas acredito que com esses ajustes (https://github.com/brunoosilva/parcelamento-no-magento/commit/d1092e6c633ca79fa858a0e016fdc459b51c63e9) resolva seu problema.

Baixe novamente e instala novamente. 

Obrigado

**Comment by brunoosilva** [comment]
Atualizei o README, dê uma olhada
